# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-03 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=100, verbose_name='Address line 1')),
                ('address2', models.CharField(blank=True, max_length=100, verbose_name='Address line 2')),
                ('zipcode', models.CharField(max_length=12, verbose_name='Zip / Postal code')),
                ('city', models.CharField(max_length=150, verbose_name='City')),
            ],
        ),
    ]
