# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=100, verbose_name='Address line 1')),
                ('address2', models.CharField(blank=True, max_length=100, verbose_name='Address line 2')),
                ('zipcode', models.CharField(max_length=12, verbose_name='Zip / Postal code')),
                ('city', models.CharField(max_length=150, verbose_name='City')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
    ]
