# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 03:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address1', models.CharField(
                    max_length=100, verbose_name='Address line 1')),
                ('address2', models.CharField(
                    blank=True, max_length=100,
                    verbose_name='Address line 2')),
                ('zipcode', models.CharField(
                    max_length=12, verbose_name='Zip / Postal code')),
                ('city', models.CharField(max_length=150,
                                          verbose_name='City')),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL)),
            ], ),
    ]
