# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 03:27
# Generated by Django 1.11.5 on 2017-09-25 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('nick_name', models.CharField(
                    blank=True, max_length=30, verbose_name='nick name')),
            ], ),
    ]
