# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-29 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=70, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.CharField(max_length=30, null=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nick_name',
            field=models.CharField(max_length=30, verbose_name='Nick name'),
        ),
    ]
