# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cover_url', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('genre', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('rating', models.IntegerField()),
                ('publisher', models.CharField(max_length=100)),
                ('release_date', models.DateTimeField(verbose_name='publishing date')),
                ('author', models.ManyToManyField(to='books.Author')),
            ],
        ),
    ]
