# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20170923_1122'),
        ('books', '0002_auto_20170923_1535'),
    ]

    operations = [
    ]
